version: "3.4"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbvolume:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redisvolume:/data

volumes:
  mongodbvolume:
  redisvolume: