version: "3.4"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devuser
      - POSTGRES_DB=postgres
    volumes:
      - postgresvolume:/var/lib/postgresql/data
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbvolume:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redisvolume:/data

volumes:
  postgresvolume:
  mongodbvolume:
  redisvolume: